<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_calculator</name>
   <tag></tag>
   <elementGuidId>4adcf0e7-1450-4f5c-b29d-a1d7e613c3c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.card-section.vk_c > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rso']/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jscontroller</name>
      <type>Main</type>
      <value>bTaGX</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsdata</name>
      <type>Main</type>
      <value>ZBX0ee;;AExnxI</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsaction</name>
      <type>Main</type>
      <value>i60oqe:Z0NzZd;ISFFIe:YzSkFd;cGuLC:Z2Ekqd;KeDSPe:w07Nsb;NdWHob:Mk4Mke</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  ผลการคำนวณ             การคำนวณและผลลัพธ์ของคุณจะปรากฏที่นี่ เพื่อให้คุณนำไปใช้ซ้ำได้                         0 (function(){
var a=document.getElementById(&quot;cwos&quot;),b;var c=parseFloat(a.innerText||a.textContent),d=c.toString();if(12>=d.replace(/^-/,&quot;&quot;).replace(/\./,&quot;&quot;).length)b=d;else if(d=c.toPrecision(12),-1!=d.indexOf(&quot;e&quot;)){var e,f,g,h=null!=(g=null==(e=d.match(/e.*$/))?void 0:null==(f=e[0])?void 0:f.length)?g:0;b=c.toPrecision(12-h-(&quot;0&quot;==d[0]?1:0)).replace(/\.?0*e/,&quot;e&quot;)}else{var k=d.match(/(^-|\.)/g),l=d.substr(0,12+(k?k.length:0));b=-1!=l.indexOf(&quot;.&quot;)?l.replace(/\.?0*$/,&quot;&quot;):l}a.textContent=b;}).call(this);         คุณสามารถค้นหานิพจน์คณิตศาสตร์โดยใช้ฟังก์ชัน เช่น: sin, cos, sqrt เป็นต้น คุณสามารถดูรายการฟังก์ชันทั้งหมดได้ที่นี่             Rad  Deg       x!         Inv      sin  sin−1       ln   ex        π      cos  cos−1      log  10x        e      tan  tan−1      √   x2        Ans  Rnd      EXP      xy  y√x             (      )      %      AC CE        7      8      9      ÷        4      5      6      ×        1     2      3      −        0      .      =      +           </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rso&quot;)/div[@class=&quot;KIy09e obcontainer mod NFQFxe&quot;]/div[1]/div[@class=&quot;card-section vk_c&quot;]/div[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rso']/div/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ผลการค้นหา'])[1]/following::div[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='การตั้งค่าภาษา'])[1]/following::div[20]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div/div</value>
   </webElementXpaths>
</WebElementEntity>
